### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by jarutis** [spark-notebook/spark-notebook#311]
It would be nice to have a progress bar showing spark tasks status after the cell is run.

**Comment by andypetrella** [comment]
Yea, I think we need to revamp this one: https://github.com/andypetrella/spark-notebook/blob/master/modules%2Fcommon%2Fsrc%2Fmain%2Fscala%2Fnotebook%2Ffront%2Fwidgets%2FSparkInfo.scala

But I'd like to screw the UI at some point to have panels (using gridster for instance), and I'd add one for:
* tachyon
* spark progress

**Comment by andypetrella** [comment]
@jarutis I pushed something similar, actually assigning a job to a cell is rather tricky specially in two cases:
* stuff running in Future/delayed, including spark ones → how to track the cell that launched them oO
* this is even more true in case of FAIR scheduler when jobs can run concurrently
* what about streams → several run for the same cell

Hence, the thing I pushed is a bit more general and shows for now quite ugly pies for current jobs.

I expect the user to be more able (and quicker) to match the pie (provided with name, id and runtime) than any heuristic ...

However, I'm expecting some feedback and comment from users (like you ^^)

**Comment by jarutis** [comment]
Thanks, I'll check :+1:

**Comment by vidma** [comment]
databricks do it so should be possiblish: https://vimeo.com/143883002#t=309s
 
> stuff running in Future/delayed, including spark ones → how to track the cell that launched them oO

one hack I'm aware of is to use job group tags (but maybe there's even a better way). so like this:
```scala
def withJobName(name: String)(job: => Unit): Unit = {
  sc.setJobGroup(name, name)
       job
       sc.clearJobGroup()
  }
}
// run the cell with
sc.withJobName {
  theClosureOfTheCellToExecute
}
```

**Comment by vidma** [comment]
discussed with @andypetrella and the above hack looks legit, with the only minor drawback that this would assume the user code not to set/override the `jobGroup`. however, we get as a bonus ability to stop the cell by using `sc.cancelJobGroup()`.

We have these tasks at least:
- [ ] add an ID to each cell, and send it to the server when execute
- [ ] forward this cell id to the replcalculator (use `sc.setJobGroup` at first)
- [ ] adapt ReplCalulator to use this id to set the job id (in the code String)
- [ ] extract cell-id from StageInfo.name, and pass to progressbar (rather trivial)
- [ ] redo progressbar to:
  * show total progress % for all running cells, near the menu/action-bar
  * split progresses per cell, and display cell progress %
  * show detailed cell stats preferably on demand (stages per cell), as number of stages could be large
- [ ] only `jobGroupId` is enough by itself, while `sc.setJobGroup` sets both `name & description`. by implementing `setJobGroupId` & `clearJobGroupId` , `description` could be left intact, to be used by user code (vidma)
- [ ] implement stopping a cell

**Comment by andypetrella** [comment]
Awesome!
I should put some effort on that early the coming week (I'll have to prepare many notebooks, hence doing that at the same should be a perfect timing!)

thanks for the detailed explanations and reviews!!!

**Comment by andypetrella** [comment]
I've done the cell id thing already, but try to see how the job thingy can be used event with asyncly created jobs... setJobGroup is thread local

**Comment by vidma** [comment]
> I've done the cell id thing already, but try to see how the job thingy can be used event with asyncly created jobs... setJobGroup is thread local

multiple jobs having the same group id sounds perfectly fine to me...

**Comment by andypetrella** [comment]
indeed, the thing is that if the job is started in a future, the code that sets the group before, and reset it after won't work right?

**Comment by vidma** [comment]
it's fine:
- we need to reset the jobGroup only in the current thread (which will run other cells)
- the other thread has/makes a thread-local copy of "config" (which includes jobGroup). if it's still running, so the code is associated with the same cell, isn't it.

**Comment by andypetrella** [comment]
Hah! That's awesome, I didn't dig that far, I just check the threadlocal thingy
let me finish that and i'll push it, so we can review

**Comment by andypetrella** [comment]
@vidma https://github.com/andypetrella/spark-notebook/pull/469 here we gooo :-)
