### ISSUE TITLE
install casbah mongodb driver

### ISSUE THREAD

**Issue by ploub** [spark-notebook/spark-notebook#547]
Hello,
Thank you for this excellent software !
I wanted to work with mongodb, I tried to install casbah with :dp + org.mongodb % casbah % 2.5.0
and I have this message : 
failed to load 'org.mongodb:casbah:jar:2.5.0 (runtime)' from ["Maven2 local (file:~/.m2/repository, releases+snapshots) without authentication", "maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication", "spark-packages (http://dl.bintray.com/spark-packages/maven/, releases+snapshots) without authentication"

I don't understand, which authentication ? I tried many things with the config files, setting different versions for the driver, but nothing works, always the same message...
Is it possible to do that with the zip folder I donwloaded or should i reconfigure the master ?

Thank you for your help !

**Comment by ploub** [comment]
I forgot to say that i have the same message trying to install classic scala mongo driver...

**Comment by meh-ninja** [comment]
Not quite sure about `0.6.2` but in `0.7.0`, with `:dp "org.mongodb" % "casbah_2.10" % "3.1.0"` the result is:

```
globalScope.jars: Array[String] = [Ljava.lang.String;@519386b1
res4: List[String] = List(/tmp/spark-notebook/repo/e0d90798-6673-458b-935d-0c14544cab1a/cache/org.mongodb/casbah-commons_2.10/jars/casbah-commons_2.10-3.1.0.jar, /tmp/spark-notebook/repo/e0d90798-6673-458b-935d-0c14544cab1a/cache/joda-time/joda-time/jars/joda-time-2.3.jar, /tmp/spark-notebook/repo/e0d90798-6673-458b-935d-0c14544cab1a/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.6.0.jar, /tmp/spark-notebook/repo/e0d90798-6673-458b-935d-0c14544cab1a/cache/com.github.nscala-time/nscala-time_2.10/jars/nscala-time_2.10-1.0.0.jar, /tmp/spark-notebook/repo/e0d90798-6673-458b-935d-0c14544cab1a/cache/org.mongodb/casbah-core_2.10/jars/casbah-core_2.10-3.1.0.jar, /tmp/spark-notebook/repo/e0d90798-6673-458b-935d-0c14544cab1a/cache/org.mon...
```

The output is similar for `:dp "org.mongodb" %% "casbah" % "2.5.0"`. This is on a clean server with a clean notebook, no settings set.

The authentication message means that the maven resolver did not use any authentication mechanism (which is correct, those maven repos do not require authentication).
