### ISSUE TITLE
Bicolor scheme on SNB list page ?

### ISSUE THREAD

**Issue by quertenmont** [spark-notebook/spark-notebook#797]
Can we have odd and even row displayed in different color ?
When you have seevral notebook, it is complicated to press the right button (right of the screen) corresponding to a specific notebook (left of the screen).

An other option (eventually prefered) would be to move the button on the left of the notebook name column.

![image](https://cloud.githubusercontent.com/assets/4639944/22198299/3a371752-e156-11e6-82f1-8e9efe449a04.png)

Loic,

**Comment by vidma** [comment]
I prefer `to move the button on the left of the notebook name column.`.
we'll see what's easier.

**Comment by quertenmont** [comment]
Fixed in #840

**Comment by quertenmont** [comment]
See also #841 as a possible (additional) option
