### ISSUE TITLE
Date and Timestamp formatting in table widget

### ISSUE THREAD

**Issue by quertenmont** [spark-notebook/spark-notebook#831]
Hello,

Currently, the Date and Timestamp is rendered as long number in the table widget,
would be nice to have them rendered properly.  (Similarly to what DataFrame.show() does for instance)

Loic,

**Comment by vidma** [comment]
which exactly datatypes you are interested in?

I see there are to timestamp conversions for `Date` and `SqlDate`. I can change them to some formatted date. probably you want a `DateTime` too?

https://github.com/spark-notebook/spark-notebook/blob/01ce39b368c8b26828cc6767814bb9fde8783871/modules/common/src/main/scala/notebook/front/widgets/Magic.scala#L52-L53

**Comment by quertenmont** [comment]
https://docs.oracle.com/javase/7/docs/api/java/sql/Timestamp.html
https://docs.oracle.com/javase/7/docs/api/java/util/Date.html

Thanks

**Comment by vidma** [comment]
default formats (`.toString`) would be:

java.sql.Timestamp -> yyyy-mm-dd hh:mm:ss.fffffffff
java.util.Date->  EEE MMM dd HH:mm:ss zzz yyyy
java.sql.date ->  yyyy-mm-dd

I guess we want to unify it. but maybe it's good as is, and we can do format unification later?

**Comment by quertenmont** [comment]
Good for me.

Thanks

--------------------------------------------------------------------------------------------
   Loic Quertenmont - Data Scientist at Kensu.io
   Phone: +32 474 831 531       Skype: loic_quertenmont
--------------------------------------------------------------------------------------------

2017-03-29 12:32 GMT+02:00 vidma <notifications@github.com>:
