### ISSUE TITLE
GeoPointsChart doesn't show an output?

### ISSUE THREAD

**Issue by crossnewbie** [spark-notebook/spark-notebook#843]
I have a Dataframe with two columns: Latitude and Longitude. I passed that to GeopointsChart. The output say "showing 1000 rows" but its not actually showing me anything. Am I going wrong somewhere or is this a bug?  [Scala [2.10.6] Spark [2.0.1] Hadoop [2.7.2]]
![untitled](https://cloud.githubusercontent.com/assets/13012191/25303530/ccc39a3e-2722-11e7-8a0d-69d7f05d0b01.png)

**Comment by maasg** [comment]
could you paste the code as well?

**Comment by crossnewbie** [comment]
`case` class review(review_id:String, user_id:String, business_id:String, stars:Double, date:String, text:String, useful:BigInt, funny:BigInt, cool:BigInt)
case class tip(text:String, date:String, likes:BigInt, business_id:String, user_id:String)
case class user(user_id:String, name:String, review_count:BigInt, yelping_since:String, friends:Array[String], useful:BigInt, funny:BigInt, cool:BigInt, fans:BigInt, 
                elite:Array[String],average_stars:Double, ompliment_hot:BigInt, compliment_more:BigInt, compliment_profile:BigInt, compliment_cute:BigInt, 
                compliment_list:BigInt, compliment_note:BigInt, compliment_plain:BigInt, compliment_cool:BigInt, compliment_funny:BigInt, compliment_writer:BigInt, 
                `compliment_photos:BigInt)`
case class Business(business_id:String, name:String, neighborhood:String, address:String, city:String, state:String, postal_code:String, latitude:Double, 
                    longitude:Double, stars:String, review_count: BigInt, is_open: String, attributes:Array[String], categories:Array[String], hours:Array[String])
case class checkin(time:String, business_id:String)
val sqlContext = new org.apache.spark.sql.SQLContext(sc)
import org.apache.spark.sql._
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
val dfBusiness = sqlContext.read.json("file:///D:/Rutgers/TM/yelp_dataset_challenge_round9/yelp_academic_dataset_business.json").toDF.as[Business]
dfBusiness.registerTempTable("business")
val distcit = dfBusiness.select($"latitude",$"longitude")
GeoPointsChart(distcit)``

**Comment by crossnewbie** [comment]
Scala [2.10.6] Spark [2.0.1] Hadoop [2.7.2]

**Comment by crossnewbie** [comment]
Apparently my data size was too large and the GeoPointsChart disaplyed the result after a long time.

**Comment by vidma** [comment]
P.S. 1000 points don't sound like very many.
might be there's some space for impriving the widget too..
