### ISSUE TITLE
Cannot save notebooks (File -> Save has no effect)

### ISSUE THREAD

**Issue by raproth** [spark-notebook/spark-notebook#845]
I'm using the current Master (build from spark-notebook.io , 0.8.0-SNAPSHOT-8d5304ca501e856fbda07b0a26a0cdc8b67b47a3 ) and having problems saving my notebook while using the default filesystem storage provider (as given in application.conf)

- File -> Save does NOT save the notebook on the filesystem
- File -> Save (with commit message) -> empty message -> does NOT save the notebook on the filesystem
- File -> Save (with commit message) -> non-empty message -> does save the notebook on the filesystem

EDIT:

CTRL + S also work fine

**Comment by raproth** [comment]
So if I understand the code correctly, File->Save (as well as File->Save (with commit message)) does call `Notebook.prototype.checkpoint_notebook` (https://github.com/spark-notebook/spark-notebook/blob/b519c8ba45dc7809068d05fa6333b67f529075b9/public/ipython/notebook/js/notebook.js)

This function seems to save ONLY if there is a valid message. But when doing File -> Save, there is no way to enter a message so `Notebook.prototype.save_notebook(message)` is never called

**Comment by vidma** [comment]
I guess this is also related to https://github.com/spark-notebook/spark-notebook/issues/846

**Comment by raproth** [comment]
not this is still open and not related to https://github.com/spark-notebook/spark-notebook/issues/846

CTRL+S works fine, but File -> Save does not work

**Comment by vidma** [comment]
apparently the menu item was not bound to any command. :rofl:

**Comment by raproth** [comment]
@vidma thanks for fixing!
