### ISSUE TITLE
Delete notebooks does not work

### ISSUE THREAD

**Issue by raproth** [spark-notebook/spark-notebook#847]
I'm using the current Master (build from spark-notebook.io , 0.8.0-SNAPSHOT-8d5304ca501e856fbda07b0a26a0cdc8b67b47a3 ) and having problems saving my notebook while using the default filesystem storage provider (as given in application.conf)

If I delete a notebook there is no effect, the notebooks is not deleted. Strangely, there is also Message in the logs

**Comment by andypetrella** [comment]
Hello @raproth can you come on the gitter channel? https://gitter.im/andypetrella/spark-notebook

I think your issues are all related to the write rights on your FS actually

**Comment by raproth** [comment]
see solution in https://github.com/spark-notebook/spark-notebook/issues/846
