### ISSUE TITLE
failed to load customDeps 

### ISSUE THREAD

**Issue by drewnoff** [spark-notebook/spark-notebook#881]
I try to add [magellan](https://spark-packages.org/package/harsha2010/magellan)  to  `customDeps` 
so my `customDeps` section looks like this:
```
"customDeps": [
    "harsha2010:magellan:1.0.4-s_2.11"
  ]
```
and I get the following error in my browser console
```
[com.jcabi.aether.Aether] #resolve(harsha2010:magellan:jar:1.0.4-s_2.11, 'runtime', com.datafellas.utils.Deps$$anon$1@57aff85e): thrown org.sonatype.aether.resolution.DependencyResolutionException(failed to load 'harsha2010:magellan:jar:1.0.4-s_2.11 (runtime)' from ["Maven2 local (file:/home/dr0ff/.m2/repository, releases+snapshots) without authentication", "maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication", "spark-packages (http://dl.bintray.com/spark-packages/maven/, releases+snapshots) without authentication", "oss-sonatype (https://oss.sonatype.org/content/repositories/releases/, releases+snapshots) without authentication"] into /tmp/spark-notebook/aether/25783b94-03a3-408f-a8d5-548350b5bc4c) out of com.jcabi.aether.Aether#fetch[237] in 5s
...
```

I also get the same error when I try to use sbt format:
```
 "customDeps": [
    "harsha2010 % magellan % 1.0.4-s_2.11"
  ]
```

The strange thing I see is that it tries to resolve `harsha2010:magellan:jar:1.0.4-s_2.11` with that extra `:jar:` added.

I tried with pre-built distribution `spark-notebook-0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.7.2`
and I also tried to build Spark Notebook from the sources `sbt -Dspark.version=2.1.1 -Dhadoop.version=2.7.0 -Dscala.version=2.11.8`

When I try to remove this dependency from `customDeps` and add it to `build.sbt` and build Spark Notebook from the sources then it works fine.

**Comment by vidma** [comment]
seems like a bug in dependency resolving in `scala 2.11`
