### ISSUE TITLE
publish latest version

### ISSUE THREAD

**Issue by antonkulaga** [spark-notebook/spark-notebook#887]
Looks like the current master is around 0.90 while latest version available at http://spark-notebook.io/ is 0.70 it would be nice to have somewhere newer there.

**Comment by vidma** [comment]
what do you mean? you can always enter any Hadoop version in  http://spark-notebook.io/ and it'll build it for you in a minute...

P.S. on the other hand, we've deprecated scala 2.10 (for play 2.5+ support), might need a little spark-notebook.io update for this.

**Comment by antonkulaga** [comment]
Sorry for typos: I mean Spark Notebook versions. Current masters version is 0.90 (a added 2 by mistake) while latest release is 0.70 The question is: where it the intermediate one?

**Comment by vidma** [comment]
well, it's `branch-0.8` and the release was published yesterday: 
https://github.com/spark-notebook/spark-notebook/releases/tag/v0.8.1 (unfortunately this still requires lots of manual testing)
