### ISSUE TITLE
"File name too long" 

### ISSUE THREAD

**Issue by antonkulaga** [spark-notebook/spark-notebook#899]
I often get "file name too long" exception in spark notebook (inside docker). 
```
<console>:116: error: File name too long
This can happen on some encrypted or legacy file systems.  Please see SI-3623 for more details.
class $iw extends Serializable {
      ^
<console>:118: error: File name too long
This can happen on some encrypted or legacy file systems.  Please see SI-3623 for more details.
class $iw extends Serializable {
```

**Comment by antonkulaga** [comment]
I have to check: mayb it is spark issue...

**Comment by vidma** [comment]
could you please provide more details on this? 

- do you see it on docker only? spark-shell? which versions?
- what is needed to do to reproduce it?

**Comment by helgaros** [comment]
try Long Path Tool program,very recommended in such case

**Comment by mrgambal** [comment]
Hi everyone!
I've run into the same problem today. After several runs of the provided Spark-101 notebook it complains like the following:

```scala
<console>:111: error: File name too long
This can happen on some encrypted or legacy file systems.  Please see SI-3623 for more details.
class $iw extends Serializable {
      ^
```

After restarting the kernel it works for next several attempts.
I suspect it might be the case of some of conundrums related to `osxfs` implementation in Docker. But this is just a wild guess.
Here is the list of SW used:

```
MacOS: 10.13.3
Docker CE Version: 18.02.0-ce-mac53 (22617)
Spark Notebook Version: http://spark-notebook.io/dl/docker/0.7.0/2.11/2.1.0/2.7.3/true/true
```

The issue (in my case) could be reproduced by simply executing the very first cell with imports for 5-6 times in a row.
Hope this may help.

**Comment by vidma** [comment]
though I'm afraid that's issue of scala shell... hopefully it'll be solved in future versions.

meanwhile restarting kernel would do...

also as a hack you may try making `/tmp` unencrypted, and/or running spark notebook from non-encrypted directory (didn't try):

> For people interested in a workaround, if you have a directory that is not encrypted, say /tmp, you can put target <<= baseDirectory { file("/tmp/sbt/") / _.toString } in ~/.sbt/0.13/global.sbt and move all the target output to that directory.
> https://issues.scala-lang.org/browse/SI-3623

**Comment by xkjyeah** [comment]
This can be solved by adding to `compilerArgs`: `"-Xmax-classfile-name", "200"`
