### ISSUE TITLE
Spark notebook configuration issues

### ISSUE THREAD

**Issue by bti2** [spark-notebook/spark-notebook#900]
I'm new to spark notebook , I'm trying to install it. I finished all instructions but when i write bin/spark-notebook this error appears
/c/ProgramData/Oracle/Java/javapath/java: Argument list too long
I don't know what to do to fix it
help please
thank uu

**Comment by frbayart** [comment]
I'm not a Windows expert but I know Windows have path size limitation may be it's your case.
Have you some virtualization on your Windows (VMWare or VirtualBox or Hyper-V) ?

What is your Windows version + edition ?

**Comment by bti2** [comment]
I don't have any virtualization on windows
My windows is 8.1 pro 
and I use spark-notebook-0.9.0-SNAPSHOT-scala-2.11.8-spark-2.1.1-hadoop-2.7.2-with-hive
thank u
