### ISSUE TITLE
New Docker image does not run because JDK7

### ISSUE THREAD

**Issue by SLMitch** [spark-notebook/spark-notebook#902]
On new image (for example http://spark-notebook.io/dl/docker/0.7.0/2.11/2.1.1/2.6.0-cdh5.10.1/true/true )
when we run and try to go to the http interface, we have a oops, the 
unsupported major.minor version 52.0
on logs.

So it is more critical than issue https://github.com/spark-notebook/spark-notebook/issues/868 where only dependencies is not good : now the docker image is not usable.

Regards

**Comment by vidma** [comment]
hi, 0.7.0 is a rather old release. 
you may try the newest code from `master` (scala 2.11 only) - if I'm not mistaken, it should use jdk8.
Use:

```shell
docker pull andypetrella/spark-notebook:0.9.0-SNAPSHOT-scala-2.11.8-spark-2.1.1-hadoop-2.7.2-with-hive
docker run -p 9001:9001 andypetrella/spark-notebook:0.9.0-SNAPSHOT-scala-2.11.8-spark-2.1.1-hadoop-2.7.2-with-hive

* for master, currently you need to change 0.7.0-SNAPSHOT -> 0.9.0-SNAPSHOT in the instructions sent to you by spark-notebook.io
```

P.S. we still need to add newly released `0.8.3` to spark-notebook.io interface and update the UI...

**Comment by vidma** [comment]
so basically it's not JDK7/8 issue, anymore...

what needs some love:
- [ ] spark-notebook.io 
- [ ] maybe improving default docker config slightly...

**Comment by vidma** [comment]
so basically it's not JDK7/8 issue, anymore... so closing this ticket.

what needs some love:
- [ ] spark-notebook.io 
- [ ] maybe improving default docker config slightly...
