### ISSUE TITLE
error: not found: value globalScope

### ISSUE THREAD

**Issue by KIC** [spark-notebook/spark-notebook#908]
I have tried several zip distributions with notebook vesion 7 and spark >= 2.0 on windows 10. but with all of them I run into the problem `error: not found: value globalScope`. I have not found any valuable soulution for it but old issues which seems to be closed for long. I have tried i.e. the solution of issue 740. However I still run into this issue so there is a chance that this issue is in fact not solved already.  

```
<console>:15: error: not found: value sparkContext
       sparkContext
       ^
<console>:12: error: not found: value globalScope
       globalScope.sparkContext.setJobGroup("cell-9B0C8136E089479A8854F670BB98036A", "run-1504598744088: sparkContext")
       ^

```

**Comment by vidma** [comment]
check broswer console for logs. probably there's something wrong in your config.

P.S. and better use it from docker. windows = asking for trouble ;)

**Comment by KIC** [comment]
I think there are still alot of people forced to use windows. However I can use the Linux Subsystem and there it works.
