### ISSUE TITLE
Redirect SLF4J log output from developer console to notebook output?

### ISSUE THREAD

**Issue by crockpotveggies** [spark-notebook/spark-notebook#913]
We're building some Spark notebooks that it appears that when using `org.slf4j.Logger` the output is redirect to the browser developer console, not the notebook cell output. Screenshot below.

In this case it would make sense to add a logback.xml that appends the output to the notebook instead. However, where is the original configuration file controlling this? A couple initial attempts have not worked. Thanks for your help.

![screen shot 2017-10-01 at 10 20 33 pm](https://user-images.githubusercontent.com/1445295/31088867-f61f8bd6-a756-11e7-8f3a-79294cee0535.png)

**Comment by vidma** [comment]
I think this was intended,  as logs can be very verbose - cell output is currently supposed to show only `stdout` & `stderr`.

I think you want to control the log config of a remote subprocess where the customized scala/spark-REPL is run.

this should be a good starting point for you: https://github.com/spark-notebook/spark-notebook/blob/master/modules/subprocess/src/main/scala/notebook/kernel/pfork/BetterFork.scala#L262-L272

**Comment by vidma** [comment]
also in case of cells running concurrent code (e.g. futures), there's no other way to associate stuff to cells than stdout/stderr.

**Comment by crockpotveggies** [comment]
Awesome thanks, and yes we did eventually realize that it is intended behavior. This is enough info for me to investigate.
