### ISSUE TITLE
org.slf4j.LoggerFactory Library giving error when compiling

### ISSUE THREAD

**Issue by GirishNA** [spark-notebook/spark-notebook#916]
Got error when compiling the project 
spark-notebook/modules/subprocess/src/main/scala/notebook/kernel/pfork/BetterFork.scala:12: object LoggerFactory is not a member of package org.slf4j
[error] import org.slf4j.LoggerFactory
[error]        ^

spark-notebook/modules/core/src/main/scala/notebook/util/Logging.scala:3: object slf4j is not a member of package org
[error] import org.slf4j.LoggerFactory
[error]            ^

**Comment by vidma** [comment]
hmm weird...  at least continuos integration build is passing though.

so you compile it on windows? which versions? can paste the command line you use?

P.S. windows is not yet fully supported so I just advice you to use docker-image which should work on windows OK...

**also you can download it pre-compiled for you at http://spark-notebook.io/**

**Comment by GirishNA** [comment]
I am using ubuntu 16.04 version and it is 64 bit machine
scala version 11.8
sbt version is 0.13.15
and i clone the project from -> git clone https://github.com/spark-notebook/spark-notebook/
cd spark-notebook
$ sbt


[spark-notebook] $ clean
[success] Total time: 2 s, completed 9 Oct, 2017 12:55:11 PM
[spark-notebook] $ reload
[info] Loading project definition from /home/girish/mywork/rapidor/spark-notebook/project
[info] Set current project to spark-notebook (in build file:/home/girish/mywork/rapidor/spark-notebook/)
[spark-notebook] $ update
[success] Total time: 15 s, completed 9 Oct, 2017 12:55:45 PM
[spark-notebook] $ compile
[info] Compiling 3 Scala sources to /home/girish/mywork/rapidor/spark-notebook/modules/sbt-dependency-manager/target/scala-2.11/classes...
[info] Compiling 5 Scala sources and 1 Java source to /home/girish/mywork/rapidor/spark-notebook/modules/subprocess/target/scala-2.11/classes...
[info] Compiling 10 Scala sources to /home/girish/mywork/rapidor/spark-notebook/modules/core/target/scala-2.11/classes...
[error] /home/girish/mywork/rapidor/spark-notebook/modules/subprocess/src/main/scala/notebook/kernel/pfork/BetterFork.scala:12: object LoggerFactory is not a member of package org.slf4j
[error] import org.slf4j.LoggerFactory
[error]        ^
[error] /home/girish/mywork/rapidor/spark-notebook/modules/subprocess/src/main/scala/notebook/kernel/pfork/BetterFork.scala:211: not found: value LoggerFactory
[error]   private lazy val log = LoggerFactory.getLogger(getClass)
[error]                          ^
[error] two errors found
[error] /home/girish/mywork/rapidor/spark-notebook/modules/core/src/main/scala/notebook/util/Logging.scala:3: object slf4j is not a member of package org
[error] import org.slf4j.LoggerFactory
[error]            ^
[error] /home/girish/mywork/rapidor/spark-notebook/modules/core/src/main/scala/notebook/util/Logging.scala:7: not found: value LoggerFactory
[error]   private[this] val log = LoggerFactory.getLogger(this.getClass)
[error]                           ^
[error] two errors found
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] one warning found
[error] (subprocess/compile:compileIncremental) Compilation failed
[error] (spark-notebook-core/compile:compileIncremental) Compilation failed
[error] Total time: 12 s, completed 9 Oct, 2017 12:56:01 PM

**Comment by vidma** [comment]
maybe you cloned the project very long time ago and didn't update the code `git pull origin master`? 
compile works file for me:

```
# git clone https://github.com/spark-notebook/spark-notebook.git

git pull origin master
sbt clean compile
....
[warn] 33 warnings found
[warn] Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.8'
[success] Total time: 173 s, completed Oct 9, 2017 12:56:14 PM
```

same with sbt console...
```
[success] Total time: 41 s, completed Oct 9, 2017 1:00:31 PM
```

**Comment by GirishNA** [comment]
i did that all steps, but then also same error coming

**Comment by vidma** [comment]
weird, just download a build from http://spark-notebook.io/ website then, for now. 
feel free to explore if this is a real issue or issue with your config...

P.S. dumb idea, you might need jdk/java8 if yours if older.

**Comment by jecazamea** [comment]
I have had the same issue
Solved by deleting the directories .m2, .ivy2, .coursier
Compilation ok after that

**Comment by vishaalkolki** [comment]
This worked for me as well. I deleted .m2 and updated maven project. Thanks

**Comment by PramudithaKaushalya** [comment]
Set your dependencies as follows.

In Maven

```
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.6.6</version>
</dependency>
``` 

In Gradle

```
dependencies {
     compile 'org.slf4j:slf4j-api:1.6.6'
}
```
