### ISSUE TITLE
spark-notebook configuration is totally ignored by spark cluster

### ISSUE THREAD

**Issue by antonkulaga** [spark-notebook/spark-notebook#929]
Whatever memory limits and core numbers I put to spark-notebook metadata they are ignored by the Spark-cluster, the default cluster memory/core configuration is used instead. It created a problem because when several notebooks are switched on I cannot add more and I also cannot configure notebook memory consumption depending on the task I have.
To ease checking it I have dockerized configuration of the hadoop/spark/spark-notebook cluster at https://github.com/antonkulaga/bigdata-docker
with the bash script that starts the stack: https://github.com/antonkulaga/bigdata-docker/blob/master/run-swarm.sh
Note: I've tried different configurations and both static and dynamic allocations, nothing works :(

**Comment by frbayart** [comment]
Hi Anton , could you share you configuration `application.conf` or metadata notebook ?

**Comment by antonkulaga** [comment]
@frbayart I enclose the metadata and notebook (note: the problem persist even for fresh notebooks, so I doubt that it has something to do with the particular config). All other configuration is at https://github.com/antonkulaga/bigdata-docker
```json
{
  "id": "a39c0010-6da4-48e5-8a3b-a5a1bbeb8fa0",
  "name": "ml_validation",
  "user_save_timestamp": "1970-01-01T00:00:00.000Z",
  "auto_save_timestamp": "1970-01-01T00:00:00.000Z",
  "language_info": {
    "name": "scala",
    "file_extension": "scala",
    "codemirror_mode": "text/x-scala"
  },
  "trusted": true,
  "sparkNotebook": null,
  "customLocalRepo": null,
  "customRepos": [
    "comp-bio-aging % default % https://dl.bintray.com/comp-bio-aging/main/",
    "denigma % default % https://dl.bintray.com/denigma/denigma-releases/",
    "releases % default % https://oss.sonatype.org/content/repositories/releases"
  ],
  "customDeps": [
    "comp.bio.aging %% adam-playground % 0.0.7-SNAP6.6",
    "com.crealytics %% spark-excel % 0.9.8",
    "org.typelevel %% frameless-cats    % 0.4.0",
    "org.typelevel %% frameless-dataset   % 0.4.0"
  ],
  "customImports": [],
  "customArgs": null,
  "customSparkConf": {
    "spark.executor.memory": "4G",
    "spark.master": "spark://spark-master:7077",
    "spark.app.name": "genome-searcher",
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
    "spark.kryo.registrator": "org.bdgenomics.adam.serialization.ADAMKryoRegistrator",
    "spark.kryoserializer.buffer.mb": 4,
    "spark.kryo.referenceTracking": "true"
  },
  "customVars": null,
  "kernelspec": {
    "name": "spark",
    "display_name": "Scala [2.11.8] Spark [2.2.0] Hadoop [2.8.1]  {Hive ✓}"
  }
}
```
[gerontomics_ml_validation.snb (1).ipynb.zip](https://github.com/spark-notebook/spark-notebook/files/1567268/gerontomics_ml_validation.snb.1.ipynb.zip)

**Comment by antonkulaga** [comment]
@frbayart I am now not sure If I understand application.conf in a right way.
When I do override (like here https://github.com/antonkulaga/bigdata-docker/blob/master/containers/spark-notebook/application.conf), should it override only default settings or also metadata inside of my notebooks?

**Comment by antonkulaga** [comment]
Looks like even deleting all overrides did not help =(

**Comment by antonkulaga** [comment]
Currently my main problem is that spark standalone does not look at spark-notebook config and gives another ammount of cores and memory, than I specify in spark-notebook
![config_problem](https://user-images.githubusercontent.com/842436/34424877-bbc21170-ec2f-11e7-9c91-12ae33af7586.png)
(you can notice that in the metadata I specified 4GB while spark gives what it has in its default config, 5GB)

**Comment by vidma** [comment]
> (you can notice that in the metadata I specified 4GB while spark gives what it has in its default config, 5GB)

first things to check could be:
- if any of spark-conf options are passed to spark standalone app?
- if custom sparkconf is set early enough for standalone mode

app UI would show all configs that are set.
