### ISSUE TITLE
sometimes dependencies are resolved but cells do not see them

### ISSUE THREAD

**Issue by antonkulaga** [spark-notebook/spark-notebook#935]
[deps_problem.zip](https://github.com/spark-notebook/spark-notebook/files/1596615/deps_problem.zip)

I have a problem that sometimes dependencies are resolved by coursier but in the cells, their packages are not seen. I enclose an example of the notebook where I have such problem. There you see that adam is in the dependencies, and coursier worked well, however, the cell does not understand the imports
 I use the latest master and following cluster config: https://github.com/antonkulaga/bigdata-docker/tree/master/conf

However, I do not know how to reproduce the problem in a robust way, sometimes everything works, sometimes - no.

**Comment by andypetrella** [comment]
probably worth looking at 
- the server logs (what is the spawned command)
- the java props containing the classpath
- execute in a cell `customJars` which holds the jars
