### ISSUE TITLE
Impossible to import new notebook on master

### ISSUE THREAD

**Issue by beckgael** [spark-notebook/spark-notebook#936]
On master sparknotebook version, i cannot upload an existing notebook, when i click on "click here", the windows opening but when i select one, i cannot apply the upload button. It's the same on chrome, firefox and opera.
Thank you for you support

**Comment by andypetrella** [comment]
hello, this should have been fixed by https://github.com/spark-notebook/spark-notebook/commit/89dd3c54f600b9dc7eb64f997dcc9ee89baae089

hth
