### ISSUE TITLE
SNB does not compile with spark 2.3.0

### ISSUE THREAD

**Issue by james64** [spark-notebook/spark-notebook#947]
Hey,

class `JobProgressListener` is removed in spark 2.3.0 as promised by deprecation warning in spark 2.2.0. This class is used within snb codebase in `SparkMonitor` class which periodically sends various updates about running jobs etc to notebook front-end.

[Here is a link](http://apache-spark-developers-list.1001551.n3.nabble.com/RFC-deprecate-SparkStatusTracker-remove-JobProgressListener-td21229.html) to spark dev mailinglist discussion where removal of this class was decided.

I will try to have a look if current functionality can be reimplemented using `SparkStatusTracker` instead. Let me know if you know something already.

**Comment by raproth** [comment]
I also tried to compile SNB with Spark 2.3. Apart from the problem you mentioned, there are also more problems (at runtime), I think thouse are related to netty (not sure)

**Comment by raproth** [comment]
james64, maybe you can get some hints how to adapt the code from the corresponding pull request from zeppelin/spark 2.3 : https://github.com/apache/zeppelin/pull/2750

**Comment by vidma** [comment]
I suggest to rewrite `SparkMonitor` from scratch for spark 2.3+ (and put in `/modules/common/src/main/spark-post-2.3` dir, old one will go in `.../spark-pre-2.3` dir)

https://github.com/apache/zeppelin/pull/2750/files#diff-58542af0ab98166a4e47ff0af919cbd5R35  should be a good start.

P.S. it's used in UI by cell progress status bars
see:
 https://github.com/spark-notebook/spark-notebook/blob/a746b48b7ac376f2e8edea73e50d435640620308/public/javascripts/notebook/job_progress.js#L45-L74

**Comment by vidma** [comment]
- [ ] I found a quick fix for `netty` conflict - it is to use `PlayAkkaHttpServer` instead of `PlayNettyServer`
- [ ] TODO: restore per-cell status bar

**Comment by vidma** [comment]
FYI addeed progressbar for spark 2.3+ in https://github.com/spark-notebook/spark-notebook/pull/977
