### ISSUE TITLE
Reading Twitter Data using Spark Streaming

### ISSUE THREAD

**Issue by ajinkyarasal** [spark-notebook/spark-notebook#949]
I am trying to build a spring mvc web application to read Twitter data using Spark Streaming.
 We are able to get the tweets but not able to shutdown the stream gracefully.
As a result first run executes successfully but in the subsequent runs, the spark process starts by itself.
and also gives the below error:

> Exception in thread "Thread-67" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): akka.actor.InvalidActorNameException: actor name [Receiver-0-1521544084060] is not unique!

**Comment by vidma** [comment]
Hi. how is this related to SparkNotebook ? 
btw, do you run that streaming app from spark-notebook ? if not you should ask Spark guys at https://github.com/apache/spark
