### ISSUE TITLE
can spark-notebook support scala 2.12

### ISSUE THREAD

**Issue by hzy5018** [spark-notebook/spark-notebook#957]

**Comment by vidma** [comment]
`Spark` itself is compiled/published only with scala versions `2.10` and `2.11`: https://mvnrepository.com/artifact/org.apache.spark/spark-core
seems like spark doesn't compile well with scala 2.12 so far  https://contributors.scala-lang.org/t/spark-and-scala-2-12/1576/4 (but I might be wrong, I did very short googling...)

so I'm afraid 2.12 wouldn't work yet...
