### ISSUE TITLE
UI related icons not showing up after loading a CSV file

### ISSUE THREAD

**Issue by nvijayap** [spark-notebook/spark-notebook#960]
Hello,

I am using this distribution - spark-notebook-master-scala-2.11.8-spark-2.3.0-hadoop-2.7.3-with-hive
Here's what I have done ...
```
val tmr = sparkSession.sqlContext.read.format("csv")
.option("header", "true")
.option("inferSchema", "true")
.load("hdfs://192.168.1.65:9000/snb/tmr1.csv")
```
This works fine ...
```
tmr.show
```
But I don't see any UI related icons/linked to be able to view the table.
Per docs, whenever a list/matrix is returned, then the UI icons/links should show up automatically.

Thanks
Naga Vijayapuram

**Comment by nvijayap** [comment]
Sorry, not an issue, as the UI icons render fine after .collect on the dataframe.

**Comment by nvijayap** [comment]
However, it will be a nice feature enhancement to render the UI icons when cell returns DF, even if a sampling from the DF is shown in the UI.

**Comment by vidma** [comment]
cell:
```
val tmr = sparkSession.sqlContext.read.format("csv")
.option("header", "true")
.option("inferSchema", "true")
.load("hdfs://192.168.1.65:9000/snb/tmr1.csv")
```
do not return anything, it just creates a value/variable `tmr`

to return you need a return statement at the end of the cell, like this:
```
val tmr = sparkSession.sqlContext.read.format("csv")
  ...
tmr
```
