### ISSUE TITLE
"customDeps" do not resolve in Spark 2.3.0

### ISSUE THREAD

**Issue by GabeChurch** [spark-notebook/spark-notebook#961]
Using the customDeps argument in the notebook to import libraries with sbt has been a great feature but breaks with 2.3.0.
For instance a notebook with metadata
```
"customDeps": [
     "mysql % mysql-connector-java % 8.0.11"
  ]
```
will allow us to do an import like
```
import com.mysql.jdbc.Driver
```
Now we have to manually place dependencies in the /lib directory or modify the build.sbt to add them at compile.

**Comment by vidma** [comment]
did you check logs (in browser console) for why is it not working?

**Comment by frbayart** [comment]
@GabeChurch are you using "sbt run" or your version come from spark-notebook.io ?
