### ISSUE TITLE
Spark-notebook build availability from S3

### ISSUE THREAD

**Issue by mambusskruj** [spark-notebook/spark-notebook#962]
Hi, spark-notebook developers,

I want to use spark-notebook's build link 
(https://s3.eu-central-1.amazonaws.com/spark-notebook/zip/spark-notebook-master-scala-2.11.8-spark-2.1.0-hadoop-2.7.2.zip?max-keys=100000)
as a source link for spark-notebook deployment in my Dockerfile. So it should be available all the time. 
Could you please tell me how long build will be available in S3 with provided link? Can I use it in described case?
 
Thanks!

**Comment by andypetrella** [comment]
Hello, that's interesting, however this link might not be the best as it is permanent for all builds and thus maybe unstable when a new build is published.

Also, we're cleaning old versions from S3 for some kinda obvious reasons :-).

That said, if you have an S3 account, it would be quite easy to store the build there.

Feel free to contact the Kensu team as well for additional help on this (as it supports the Spark Notebook as well): contact@kensu.io.
