### ISSUE TITLE
Disabled Open SparkUI link after rebuild

### ISSUE THREAD

**Issue by Agent1101** [spark-notebook/spark-notebook#970]
Hi,
I rebuild in `ubuntu 18.10 cosmic, JDK8` with 
`sbt -D"spark.version"="2.3.2" -D"hadoop.version"="2.7.7" -D"jets3t.version"="0.7.1" -Dmesos.version="0.26.0"`
and works fine and spark jobs can be accessed via `http://mylocal:4040/jobs/` but the link is disabled!

![no-sparkui](https://user-images.githubusercontent.com/30620332/48626469-d5c4f600-e9a9-11e8-8ff2-567402296f87.png)

**Comment by vidma** [comment]
Hi,

that's a known issue with spark 2.3+ only - in spark 2.3 there's no spark jobs monitoring implemented (due to a changed spark API, see https://github.com/spark-notebook/spark-notebook/issues/953 )

on the other hand spark 2.2 would have the spark ui and job tracking...
